// <auto-generated />
using System;
using CarRentalApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRentalApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRentalApp.Models.Accident", b =>
                {
                    b.Property<int>("AccidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccidentId"));

                    b.Property<DateTime>("AccidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AccidentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccidentStatus")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveLicence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriveLicenceOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverCompanyOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverIdentity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverIdentityOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DriverNameOther")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TrafficreportId")
                        .HasColumnType("int");

                    b.HasKey("AccidentId");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("TrafficreportId");

                    b.ToTable("Accidents");
                });

            modelBuilder.Entity("CarRentalApp.Models.AccidentAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId");

                    b.ToTable("accidentAttachments");
                });

            modelBuilder.Entity("CarRentalApp.Models.AccidentPicAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccidentId");

                    b.ToTable("accidentPicAttachments");
                });

            modelBuilder.Entity("CarRentalApp.Models.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsuranceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InsuranceId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("CarRentalApp.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("BranchNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchnameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("AccidenStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BDCheckNumber")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("BDFormNumber")
                        .HasColumnType("datetime2");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<int>("ColourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDCartNumber")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDCheckNumber")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EDFormNumber")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InsuraceStatus")
                        .HasColumnType("int");

                    b.Property<int>("ManufactorerId")
                        .HasColumnType("int");

                    b.Property<int>("ModeelId")
                        .HasColumnType("int");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Yearfmanufacture")
                        .HasColumnType("datetime2");

                    b.Property<int>("classificationId")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("BranchId");

                    b.HasIndex("ColourId");

                    b.HasIndex("ManufactorerId");

                    b.HasIndex("ModeelId");

                    b.HasIndex("classificationId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CarRentalApp.Models.ClaimAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("carClaimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("carClaimId");

                    b.ToTable("ClaimAttachments");
                });

            modelBuilder.Entity("CarRentalApp.Models.ClaimStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int>("carClaimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("carClaimId")
                        .IsUnique();

                    b.ToTable("ClaimStatuses");
                });

            modelBuilder.Entity("CarRentalApp.Models.Classification", b =>
                {
                    b.Property<int>("classificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("classificationId"));

                    b.Property<string>("classificationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("classificationId");

                    b.ToTable("Classifications");
                });

            modelBuilder.Entity("CarRentalApp.Models.Colour", b =>
                {
                    b.Property<int>("ColourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColourId"));

                    b.Property<string>("ColourNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColourNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ColourId");

                    b.ToTable("Colour");
                });

            modelBuilder.Entity("CarRentalApp.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("CompanyNameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Companys");
                });

            modelBuilder.Entity("CarRentalApp.Models.Estimation", b =>
                {
                    b.Property<int>("EstimationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstimationId"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<decimal>("EstimationAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EstimationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EstimationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstimationSide")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstimationId");

                    b.HasIndex("AccidentId");

                    b.ToTable("Estimations");
                });

            modelBuilder.Entity("CarRentalApp.Models.Insurance", b =>
                {
                    b.Property<int>("InsuranceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsuranceId"));

                    b.Property<DateTime>("BDPolicyNumber")
                        .HasColumnType("datetime2");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EDPolicyNumber")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhothPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InsuranceId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Insurances");
                });

            modelBuilder.Entity("CarRentalApp.Models.Manufactorer", b =>
                {
                    b.Property<int>("ManufactorerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManufactorerId"));

                    b.Property<string>("ManufactorNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManufactorNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManufactorerId");

                    b.ToTable("Manufactorers");
                });

            modelBuilder.Entity("CarRentalApp.Models.Modeel", b =>
                {
                    b.Property<int>("ModeelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeelId"));

                    b.Property<int>("ManufactorerId")
                        .HasColumnType("int");

                    b.Property<string>("ModeelNameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeelNameEn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeelId");

                    b.HasIndex("ManufactorerId");

                    b.ToTable("Modeels");
                });

            modelBuilder.Entity("CarRentalApp.Models.Trafficreport", b =>
                {
                    b.Property<int>("TrafficreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrafficreportId"));

                    b.Property<string>("TrafficreportName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrafficreportId");

                    b.ToTable("Trafficreports");
                });

            modelBuilder.Entity("CarRentalApp.Models.UserAccount", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.HasIndex("BranchId");

                    b.ToTable("userAccounts");
                });

            modelBuilder.Entity("CarRentalApp.Models.carClaim", b =>
                {
                    b.Property<int>("carClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("carClaimId"));

                    b.Property<int>("AccidentId")
                        .HasColumnType("int");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("ClaimAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClaimStatus")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<int>("EstimationId")
                        .HasColumnType("int");

                    b.Property<string>("carClaimNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("carClaimId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("EstimationId");

                    b.ToTable("carClaim");
                });

            modelBuilder.Entity("CarRentalApp.Models.Accident", b =>
                {
                    b.HasOne("CarRentalApp.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Trafficreport", "Trafficreport")
                        .WithMany()
                        .HasForeignKey("TrafficreportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Trafficreport");

                    b.Navigation("company");
                });

            modelBuilder.Entity("CarRentalApp.Models.AccidentAttachment", b =>
                {
                    b.HasOne("CarRentalApp.Models.Accident", "Accident")
                        .WithMany("accidentAttachment")
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("CarRentalApp.Models.AccidentPicAttachment", b =>
                {
                    b.HasOne("CarRentalApp.Models.Accident", "Accident")
                        .WithMany()
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("CarRentalApp.Models.Attachment", b =>
                {
                    b.HasOne("CarRentalApp.Models.Insurance", "insurance")
                        .WithMany("Attachments")
                        .HasForeignKey("InsuranceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("insurance");
                });

            modelBuilder.Entity("CarRentalApp.Models.Car", b =>
                {
                    b.HasOne("CarRentalApp.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Colour", "Colours")
                        .WithMany()
                        .HasForeignKey("ColourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Manufactorer", "Manufactorer")
                        .WithMany("Cars")
                        .HasForeignKey("ManufactorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Modeel", "Modeel")
                        .WithMany("Cars")
                        .HasForeignKey("ModeelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Classification", "Classification")
                        .WithMany()
                        .HasForeignKey("classificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Classification");

                    b.Navigation("Colours");

                    b.Navigation("Manufactorer");

                    b.Navigation("Modeel");
                });

            modelBuilder.Entity("CarRentalApp.Models.ClaimAttachment", b =>
                {
                    b.HasOne("CarRentalApp.Models.carClaim", "carClaim")
                        .WithMany("ClaimAttachments")
                        .HasForeignKey("carClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("carClaim");
                });

            modelBuilder.Entity("CarRentalApp.Models.ClaimStatus", b =>
                {
                    b.HasOne("CarRentalApp.Models.carClaim", null)
                        .WithOne("claimStatus")
                        .HasForeignKey("CarRentalApp.Models.ClaimStatus", "carClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CarRentalApp.Models.Estimation", b =>
                {
                    b.HasOne("CarRentalApp.Models.Accident", "Accident")
                        .WithMany()
                        .HasForeignKey("AccidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accident");
                });

            modelBuilder.Entity("CarRentalApp.Models.Insurance", b =>
                {
                    b.HasOne("CarRentalApp.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("CarRentalApp.Models.Modeel", b =>
                {
                    b.HasOne("CarRentalApp.Models.Manufactorer", "Manufactorer")
                        .WithMany()
                        .HasForeignKey("ManufactorerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manufactorer");
                });

            modelBuilder.Entity("CarRentalApp.Models.UserAccount", b =>
                {
                    b.HasOne("CarRentalApp.Models.Branch", "Branch")
                        .WithMany("Users")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CarRentalApp.Models.carClaim", b =>
                {
                    b.HasOne("CarRentalApp.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRentalApp.Models.Estimation", "Estimation")
                        .WithMany("carClaims")
                        .HasForeignKey("EstimationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estimation");

                    b.Navigation("company");
                });

            modelBuilder.Entity("CarRentalApp.Models.Accident", b =>
                {
                    b.Navigation("accidentAttachment");
                });

            modelBuilder.Entity("CarRentalApp.Models.Branch", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CarRentalApp.Models.Estimation", b =>
                {
                    b.Navigation("carClaims");
                });

            modelBuilder.Entity("CarRentalApp.Models.Insurance", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("CarRentalApp.Models.Manufactorer", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalApp.Models.Modeel", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarRentalApp.Models.carClaim", b =>
                {
                    b.Navigation("ClaimAttachments");

                    b.Navigation("claimStatus")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
